# Generated by Django 5.0.7 on 2024-10-18 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_boardmodel_good_alter_boardmodel_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='good_users',
            field=models.ManyToManyField(blank=True, related_name='good_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
